version: '3.8'
services:
  mysql:
    image: mysql:8
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: Library
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - library-net

  node:
    build: .
    container_name: node-container
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - DB_NAME=Library
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    networks:
      - library-net

volumes:
  mysql-data:

networks:
  library-net:
    driver: bridge
